eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://$(EUREKA_HOST:localhost):$(EUREKA_PORT:8761)/eureka/
  

spring:
  application:
    name: FAVOURITE-SERVICE