server:
  port: 9091

spring:
  cloud:
    gateway:
      routes:
        - id: searchservice
          uri: http://localhost:8012/
          predicates:
            - Path=/api/search/**

        - id: userservice
          uri: http://localhost:8081/
          predicates:
            - Path=/api/user/**

        - id: favoriteservice
          uri: http://localhost:8088/
          predicates:
            - Path=/api/fav/**